version: '3'

services:

  mysqldb:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 36AT3crgbhawYH
      MYSQL_DATABASE: parkinglot
    ports:
      - "3306:3306"
    volumes:
      - "./dbdata:/var/lib/mysql:rw"